version: '3.8'

services:
  # Qdrant vector database - core component for embedding storage
  qdrant:
    image: qdrant/qdrant:v1.7.0
    container_name: document_search_qdrant
    ports:
      - "6333:6333"  # REST API port
      - "6334:6334"  # gRPC port (optional, for high-performance scenarios)
    volumes:
      - qdrant_storage:/qdrant/storage
    environment:
      # Enable web UI for debugging and monitoring
      QDRANT__SERVICE__HTTP_PORT: 6333
      QDRANT__WEB_UI__ENABLED: true
    restart: unless-stopped
    networks:
      - document_search_network

  # Main application service
  document-search-api:
    build: .
    container_name: document_search_api
    ports:
      - "8000:8000"
    volumes:
      # Mount local documents directory - critical for accessing your files
      - "C:/Users/Nesterenko Anton/Desktop/МІА ОІЗ:/app/documents:ro"
      # Mount for logs and temporary files
      - ./logs:/app/logs
    environment:
      # Vector database connection
      QDRANT_HOST: qdrant
      QDRANT_PORT: 6333
      # Document processing settings
      DOCUMENTS_PATH: /app/documents
      # ML model settings - using multilingual model for Ukrainian text
      EMBEDDING_MODEL: sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2
      # Application settings
      LOG_LEVEL: INFO
      MAX_CHUNK_SIZE: 1000
      CHUNK_OVERLAP: 200
    depends_on:
      - qdrant
    restart: unless-stopped
    networks:
      - document_search_network

volumes:
  qdrant_storage:
    driver: local

networks:
  document_search_network:
    driver: bridge